### ISSUE TITLE
Missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by skiniry** [jipingw/RiboDiPA#1]
Hi, 

I'm trying to run this with mouse alignments (gtf file is gencode basic m14), but when I get to this step: result.pst <- RiboDiPA(data=data.binned, classlabel=classlabel,method=c('gtxr','qvalue'))

I'm getting the following error:
Error in if (all(s.tmp > 0)) { : missing value where TRUE/FALSE needed

Running it with the example bam files/gtf file works fine.

**Comment by jipingw** [comment]
Thanks for reporting this issue. We noticed this problem, and will upload an updated version very soon.

**Comment by jipingw** [comment]
@skiniry Could you give it a try? we just updated the codes. thanks.

**Comment by skiniry** [comment]
Yes it's working now, thanks for the quick fix.
