### ISSUE TITLE
Error related with GTF file

### ISSUE THREAD

**Issue by pabloaguirreazorin** [jipingw/RiboDiPA#11]
Dear all,

I am using RiboDiPA 1.10.0 in R version 4.3.3, and when I run the wrapperFunction (RiboDiPA), it failed in the indexing step:

`Indexing`
`Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_01/B17_01Aligned.toTranscriptome.out.bam`
`[E::hts_idx_push] Chromosome blocks not continuous`
`[E::sam_index] Read 'LH00587:21:227YCTLT4:6:1101:16416:1070_GNCATAGT' with ref_name='ENSRNOT00000098729', ref_length=4966, flags=0, pos=4393 cannot be indexed`
`Error in FUN(X[[i]], ...) : failed to build index`
`  file:` 
`Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_01/B17_01Aligned.toTranscriptome.out.bam`
`Calls: RiboDiPA ... <Anonymous> -> <Anonymous> -> sapply -> sapply -> lapply -> FUN`
`Execution halted`

I also tried with the secuencial pipeline, but the psiteMapping() function threw the following error:

`Error in GenomicFeatures::makeTxDbFromGFF(gtf_file):` 
`Cannot detect whether 'file' is a GFF3 or GTF file. Please use the 'format' argument to specify the format ("gff3" or "gtf").`
`Calls: psiteMapping -> <Anonymous>`
`Execution halted`

GenomicFeatures version is 1.54.1, I am using the identical GTF file used to produce the experimental alignments (Ensembl release 112) and I also tried with the BAM files aligned to the genome, but i still have the same problems. 

Could you provide me some insights about what it could be happening (if possible), please?

Thanks very much in advance

Session info:
 [1] RiboDiPA_1.10.0             GenomicAlignments_1.38.0
 [3] SummarizedExperiment_1.32.0 MatrixGenerics_1.14.0
 [5] matrixStats_1.4.1           GenomicFeatures_1.54.1
 [7] AnnotationDbi_1.64.1        Biobase_2.62.0
 [9] Rsamtools_2.18.0            Biostrings_2.70.1
[11] XVector_0.42.0              GenomicRanges_1.54.1
[13] GenomeInfoDb_1.38.1         IRanges_2.36.0
[15] S4Vectors_0.40.2            BiocGenerics_0.48.1

**Comment by nayanvs** [comment]
I had similar error which was resolved when I used sorted BAM files. 
Additionally, I forked this repository to resolve indexing error. You may explore them for a chance.

**Comment by jipingw** [comment]
It's difficult for me to tell what the problem is. If you could share partial data sets, ie. .bam and GTF file, I could look into it. Please contact me by email. jzwang@northwestern.edu

**Comment by jipingw** [comment]
see my reply to Thread #12. It's due to the contaminated ribo-seq data (for the error "attempt to set index 10/10 in SET_STRING_ELT".  I will release a new version that can get around of this issue. In the meanwhile, you should check your bam file, and make sure there is no contamination (i.e. non ribo-seq reads, and the alignment was extremely strange or invalid).
