### ISSUE TITLE
Error at the binning step

### ISSUE THREAD

**Issue by gowgowuk** [jipingw/RiboDiPA#13]
Hello,

I've been trying to run the pipeline but got an error. Running individual steps, it looks like it happens at the binning step. I got the following error:
Data binning ...
Error in { : 
  task 23878 failed - "length of 'dimnames' [2] not equal to array extent"
  
  The test data you can download via the package works fine and the first step p-site mapping works fine too.

Many thanks

Philippe

**Comment by gowgowuk** [comment]
My Apologies! While I was preparing the files to send you, I realised that the gtf used for the script was a different version from the one used for alignment. Thank you for you prompt reply.

**Comment by jipingw** [comment]
I am glad you figured out this. I hope that will clear out the errors.
