### ISSUE TITLE
installation problem and error in RiboDiPA function

### ISSUE THREAD

**Issue by gittina** [jipingw/RiboDiPA#2]
Hi,
I tried to install your package with the command as specified in the readme file. However, the installation did not succeed. R says **"‘RiboDiPA’ is not available for this version of R".**  Then, I downloaded the zip folder and loaded the package (and all the related dependencies) within an R script. 

I run the RiboDiPA pipeline with the command: 
`result.pip <- RiboDiPA(bam_file_list = bam_files, gtf_file = gtf_path, classlabel = classlabel, cores=20)`, 
where bam files were obtained from the genomic alignments. The gtf is the one provided during the alignment step (with STAR).
classLabel is:

```
classlabel <- data.frame(condition = c("SMA","SMA","WT","WT","WT"),
                          comparison=c(2,2,1,1,1))
```

The execution halts during the coverage computation with the error message: - **"object '_RiboDiPA_psitecal' not found"**. 
Do you have any suggestion?

Thanks,
Martina

**Comment by jipingw** [comment]
Hi I am in the process to submit the package to bioconductor. It seems bioconductor keeps warning me to require R4.1 instead of current version of R4.03.  I am still trying to figure out some small bugs, hopefully it wll be done today. Please stay tuned.

**Comment by gittina** [comment]
Thanks, we'll wait. I'll keep the issue open and then I'll let you know once I will have it downloaded from bioconductor.

**Comment by bsaleme** [comment]
Same here, I thought I had something wrong with my settings but I'll wait. Thank you for building this useful tool and I look forward to trying it out.

**Comment by kerenli** [comment]
There is a function named "psiteCal" written in Rcpp, which is called within a foreach parallel loop within function ".pMappingAll". If you do not install package, you may have to add source command within that foreach loop pointing to the physical location of file "centerCPP.cpp".

Search "return(.pMappingChr" in "package.R", and add a line above it:
        sourceCpp("_YOURPATH_/centerCPP.cpp")
and also remove "psiteCal" from ".export" to ".noexport" just one more line above.

Another issue I am curious is, the error message should be "object '_RiboDiPA_psiteCal' not found" rather than "object '_RiboDiPA_psitecal' not found". Would you mind if provide me your error message log?

**Comment by kerenli** [comment]
For example:

        results <- foreach(i=seq_along(chrom), .export=c(".pMappingChr",
        ".intersectionStrict", ".createAnno", ".psiteOffset"), .noexport="psiteCal", 
        .packages=c("Rsamtools", "GenomicAlignments", "GenomicFeatures",
        "data.table", "Rcpp"), .multicombine=TRUE) %dopar%
            {
                sourceCpp("_/Users/user1/My Documents/RiboDiPA-master_/src/centerCPP.cpp")
                return(.pMappingChr(bam=bam_file_list[k], all_genes=all_genes,
                    ch=chrom[i], psite.mapping=psite.mapping))
            }
replace italic part by your downloaded RiboDiPA package directory.

**Comment by jipingw** [comment]
@bsaleme  @gittina  I changed the required version from 4.1 back to 4.0. I hope you should be able to install it. (I changed 4.0 to 4.1 in the first place because bioconductor keep warning me to change to 4.1). R 4.1 is not available from CRAN yet.

**Comment by gittina** [comment]
> @bsaleme @gittina I changed the required version from 4.1 back to 4.0. I hope you should be able to install it. (I changed 4.0 to 4.1 in the first place because bioconductor keep warning me to change to 4.1). R 4.1 is not available from CRAN yet.

I have the 4.0 version, and I'm still not able to install it via bioconductor.

**Comment by jipingw** [comment]
@gittina it hasn't been approved by bioconductor yet. You have to install from the source.I am trying to get it approved these days. you down load it, use R CMD build and R CMD instlall to install it.

**Comment by gittina** [comment]
I installed it from the source as you suggested. I executed again the command:
`result.pip <- RiboDiPA(bam_file_list = bam_files, gtf_file = gtf_path, classlabel = classlabel, cores=20)`

And I got this error:

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'which': $ operator is invalid for atomic vectors
```

**Comment by jipingw** [comment]
@gittina  could you post your entire R codes block, so we could better detect which step might have issue? thanks.

**Comment by kerenli** [comment]
@gittina There are multiple functions called by RiboDiPA(). Basically, RiboDiPA() is a wrapper function including P-site mapping, data binning and pattern similarity test. Could you please run the following codes line by line and send us your log?

```
data.psite <- psiteMapping(bam_file_list = bam_file_list, 
    gtf_file = gtf_path, cores = 20)
data.binned <- dataBinning(data = data.psite$coverage, cores = 20)
result.pst <- diffPatternTest(data = data.binned, 
    classlabel = classlabel)
```

**Comment by gittina** [comment]
Sorry, the previous error was a slip in my code. I then ran it line by line as you suggested with the default options and I finally also obtained the plots.
