### ISSUE TITLE
Error in "Computing P-site offsets"

### ISSUE THREAD

**Issue by pspealman** [jipingw/RiboDiPA#5]
Hello,

Just getting started using RiboDiPA - while using the tutorial data everything works fine. However, when using my own data I encounter an error during the "Computing P-site offsets" section.

Error:

> Computing P-site offsets 
> Error in `[.data.table`(offsets, is.na(offset), `:=`(offset, best.offset)) : 
>   RHS of assignment to existing column 'offset' is zero length but not NULL. If you intend to delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_. If you are trying to change the column type to be an empty list column then, as with all column type changes, provide a full length RHS vector such as vector('list',nrow(DT)); i.e., 'plonk' in the new column.

  
 Code:
```
 bam_file_list <- c("RPF_DGY1743_R1.10pct.bam", "RPF_DGY1743_R2.10pct.bam",
   "RPF_DGY1657_R1.10pct.bam", "RPF_DGY1657_R2.10pct.bam")
names.sample <- sub("(.*\\/)([^.]+)(\\.[[:alnum:]]+$)", "\\2", 
                    bam_file_list)
gtf_file <- c("Saccharomyces_cerevisiae.R64-1-1.50.gtf")

classlabel <- data.frame(
  condition = c("evolved", "evolved", "ancestor", "ancestor"),
  comparison = c(2, 2, 1, 1)
)
rownames(classlabel) <- names.sample

result.pip <- RiboDiPA(bam_file_list, gtf_file, classlabel, cores = 2)
```

I made both the bams and gtf available here:
[https://github.com/pspealman/Project_Carolino](https://github.com/pspealman/Project_Carolino)

Thank you for any assistance you can provide.

**Comment by jipingw** [comment]
Hi, Thanks for you note. We will trying to figuring it out.

**Comment by jipingw** [comment]
The P-siete mapping function calculates offset rule by maximizing read counts near TSSs. The current function only utilizes the perfect match reads, which are defined that the read length equals the two tend coordinates difference. However your data set only contains 15 reads that satisfy this condition. Did you trim the adapter sequence appropriately or was the sequencing quality was very low? this usually shouldn't happen in the Ribo-seq data.

**Comment by pspealman** [comment]
Yes - you are absolutely right. It looks like a polyA tailing method was used during library construction. We trimmed differently and are now able to run without error. 
Thank you very much for your help.
